### ISSUE TITLE
SPARC: fc-cache referenced symbol not found

### ISSUE THREAD

**Issue by robdaemon** [tribblix/build#11]
Running fc-cache from TRIBsys-lib-fontconfig 2.12.6.1 gets you a referenced symbol not found error:

```
root@robblade:/root# fc-cache
ld.so.1: fc-cache: fatal: relocation error: file /usr/lib/libfontconfig.so.1: symbol __popcountsi2: referenced symbol not found
root@robblade:/root# objdump -t /usr/lib/libfontconfig.so.1 | grep pop
00000000         *UND*  00000000              __popcountsi2
```

**Comment by ptribble** [comment]
Hm. I don't see that error, although it's clearly present if I dig deeper.

The problem is that libfontconfig is explicitly using a gcc builtin, which the build process isn't allowing for. I should rebuild the packages (and probably bump the fontconfig version while we're at it).

Thanks for the report.

**Comment by ptribble** [comment]
I've pushed a rebuilt package to the repo which should fix this.

Thanks again!
